language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - 12
  - 10
  - 8
install:
  - npm install
  - npm install --global npx
script: npm test
after_success: if [ '$TRAVIS_OS_NAME' = 'linux' ]; then npm run coverage; fi
