language: node_js
os:
  - windows
  - linux
  - osx
node_js:
  - 12
  - 10
  - 8
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
install:
  - npm install
  - npm install --global npx
script: npm test
after_success: npm run coverage
